<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <Company>Starion Group S.A.</Company>
        <Description>CDP4 DAL Unit tests</Description>
        <Copyright>Copyright © Starion Group S.A.</Copyright>
        <RepositoryUrl>https://github.com/STARIONGROUP/COMET-SDK-Community-Edition.git</RepositoryUrl>
        <IsPackable>false</IsPackable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CDP4Dal\CDP4Dal.csproj" />
        <Reference Include="System.ComponentModel.Composition" />
        <Reference Include="System.Net.Http" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.dotMemoryUnit" Version="3.2.20220510" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="NUnit" Version="4.6.1" />
        <PackageReference Include="NUnit.Console" Version="3.22.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.2.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.msbuild" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup Label="build-only dependencies">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <None Update="DAL\files\SiteDirectory.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <Compile Include="..\CDP4Dal.NetCore.Tests\AssemblerTestFixture.cs">
        <Link>AssemblerTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\Composition\AvailableDalsTestFixture.cs">
        <Link>Composition\AvailableDalsTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\Composition\DalExportAttributeTestFixture.cs">
        <Link>Composition\DalExportAttributeTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\DAL\CredentialsTestFixture.cs">
        <Link>DAL\CredentialsTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\DAL\DalTestFixture.cs">
        <Link>DAL\DalTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\DAL\ProxySettingsTestFixture.cs">
        <Link>DAL\ProxySettingsTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\DtoRouteResolverTestFixture.cs">
        <Link>DtoRouteResolverTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\Events\BeforeWriteEventArgsTestFixture.cs">
        <Link>Events\BeforeWriteEventArgsTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\MessageBusTestFixture.cs">
        <Link>MessageBusTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\Operations\OperationContainerTestFixture.cs">
        <Link>Operations\OperationContainerTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\Operations\OperationTestFixture.cs">
        <Link>Operations\OperationTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\Operations\PostOperationTestFixture.cs">
        <Link>Operations\PostOperationTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\Operations\ThingTransactionTestFixture.cs">
        <Link>Operations\ThingTransactionTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\Operations\TransactionContextResolverTestFixture.cs">
        <Link>Operations\TransactionContextResolverTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\Operations\TransactionContextTestFixture.cs">
        <Link>Operations\TransactionContextTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\Permission\CopyPermissionHelperTestFixture.cs">
        <Link>Permission\CopyPermissionHelperTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\Permission\PermissionServiceTestFixture.cs">
        <Link>Permission\PermissionServiceTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\SecureStringExtensionsTestFixture.cs">
        <Link>SecureStringExtensionsTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\SessionTestFixture.cs">
        <Link>SessionTestFixture.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\Utilities\GuardTestFixtures.cs">
        <Link>Utilities\GuardTestFixtures.cs</Link>
      </Compile>
      <Compile Include="..\CDP4Dal.NetCore.Tests\UtilsTestFixture.cs">
        <Link>UtilsTestFixture.cs</Link>
      </Compile>
    </ItemGroup>
</Project>
